-- Add view_count column to posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;

-- Create post_views table to track unique views per user per video
CREATE TABLE IF NOT EXISTS post_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_post_views_post_id ON post_views(post_id);
CREATE INDEX IF NOT EXISTS idx_post_views_user_id ON post_views(user_id);

-- Function to record a view (only counts once per user per video)
CREATE OR REPLACE FUNCTION record_video_view(p_post_id BIGINT, p_user_id BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
  inserted BOOLEAN;
BEGIN
  -- Try to insert, ignore if already exists
  INSERT INTO post_views (post_id, user_id)
  VALUES (p_post_id, p_user_id)
  ON CONFLICT (post_id, user_id) DO NOTHING;

  -- Check if we actually inserted a new row
  GET DIAGNOSTICS inserted = ROW_COUNT;

  -- If we inserted a new view, increment the counter on the post
  IF inserted THEN
    UPDATE posts SET view_count = COALESCE(view_count, 0) + 1 WHERE id = p_post_id;
    RETURN TRUE;
  END IF;

  RETURN FALSE;
END;
$$ LANGUAGE plpgsql;
